import "98.css";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily:
            '"Pixelated MS Sans Serif", "MS Sans Serif", "Microsoft Sans Serif", sans-serif',
          fontSize: "12px",
        }}
      >
        {children}
      </body>
    </html>
  );
}
